var User = require('../users/userModel.js'),
    Presentation  = require('./presentationModel.js'),
    Q    = require('q'),
    mongoose = require('mongoose'),
    Feedback = require('../feedback/feedbackModel'),
    Schema = mongoose.Schema;
    //jwt  = require('jwt-simple');


module.exports = {
  create: function(req, res, next){
    //will need user to also send back the token so that the userid can be grabbed;
    var title = req.body.title,
        date  = req.body.date,
        presentationid,
    //need this to convert the userId into something that mongod will recognize
        _presenter = mongoose.Types.ObjectId(req.body.userid),
        findUser = Q.nbind(User.findOne, User),
        create = Q.nbind(Presentation.create, Presentation);

    var newPresentation = {
      _presenter: _presenter,
      title: title, 
      date: date
    };

  //create a new presentation in the database
  create(newPresentation)
  .then(function(presentation){
    //id for models automatically generated by mongoose
      presentationid = presentation.id;
      // var userId = presentation.userId;
      // res.json({presentation_id: presentationId});
  })

  findUser({_id:_presenter}).then(function (user) {
    if (!user) {
      next(new Error('Cannot find user'));
    } else {
      user.presentations.push(presentationid)
      user.save();
      console.log(user);
      res.json({presentation_id: presentationid});
    }
  })
  .fail(function (error) {
    next(error);
  });
},
  //obtain presentation data from a given date by id
  onePres: function(req, res, next){
    var presentationId = mongoose.Types.ObjectId(req.params.id);
    Presentation.findOne({_id: presentationId})
                .populate('feedbacks')
                .exec(function(err, presentations){
                  if(err) console.log(err);
                  res.json(presentations)
                })
  },

  allPres: function(req, res, next){
    var userid = req.params.userid;
    Presentation.find({_presenter: userid})
        .populate('feedbacks')
        .then(function(user){
          res.json(user)
        })
  }
};


