var User = require('../users/userModel.js'),
    Presentation  = require('./presentationModel.js'),
    Q    = require('q'),
    mongoose = require('mongoose'),
    Schema = mongoose.Schema;
    //jwt  = require('jwt-simple');


module.exports = {
  create: function(req, res, next){
    //will need user to also send back the token so that the userid can be grabbed;
    var title = req.body.title,
        date  = req.body.date,
        presentationid,
    //need this to convert the userId into something that mongod will recognize
        _presenter = mongoose.Types.ObjectId(req.body.userid),
        findUser = Q.nbind(User.findOne, User),
        create = Q.nbind(Presentation.create, Presentation);

    var newPresentation = {
      _presenter: _presenter,
      title: title, 
      date: date
    };

  //create a new presentation in the database
  create(newPresentation)
  .then(function(presentation){
    //id for models automatically generated by mongoose
      presentationid = presentation.id;
      // var userId = presentation.userId;
      // res.json({presentation_id: presentationId});
  })

  findUser({_id:_presenter}).then(function (user) {
    if (!user) {
      next(new Error('Cannot find user'));
    } else {
      user.presentations.push(presentationid)
      user.save();
      console.log(user);
      res.json({presentation_id: presentationid});
    }
  })
  .fail(function (error) {
    next(error);
  });

  
  
      


  /* is this possible?
    var justcreated = create(newPresentation)

    
  */
  },
  //obtain presentation data from a given date by id
  onePres: function(req, res, next){
    //presentationId might be retrievable from URL
    var presentationId = req.body.presentationId;

    var findPres = Q.nbind(Presentation.findOne, Presentation);

    findPres({presentationId: presentationid})
    .then(function(presentation){
      if(presentation){
        res.json(presentation.scores);
      }
      else{
        console.log('error retrieving presentation info')
      }
    })
  }

};


