var User = require('../users/userModel.js'),
    Presentation  = require('./presentationModel.js'),
    Q    = require('q'),
    mongoose = require('mongoose'),
    Schema = mongoose.Schema;
    //jwt  = require('jwt-simple');


module.exports = {
  create: function(req, res, next){
    var title = req.body.title,
        date  = req.body.date,
        userid = req.body.userid,
        //findUser = Q.nbind(User.findOne, User), //tdo remove
        create = Q.nbind(Presentation.create, Presentation);

    var newPresentation = {
      userid: userid,
      title: title, 
      date: date,
      scores: {type: Schema.ObjectId, ref: 'FeedbackSchema'}
    };

  //create a new presentation in the database
  create(newPresentation)
  .then(function(presentation){
    //id for models automatically generated by mongoose
      var presentationId = presentation.id;
      var userId = presentation.userId;
      res.json({presentation_id: presentationId});
  });
  
      


  /* is this possible?
    var justcreated = create(newPresentation)

    
  */
  },
  //obtain presentation data from a given date by id
  onePres: function(req, res, next){
    //presentationId might be retrievable from URL
    var presentationId = req.body.presentationId;

    var findPres = Q.nbind(Presentation.findOne, Presentation);

    findPres({presentationId: presentationid})
    .then(function(presentation){
      if(presentation){
        res.json(presentation.scores);
      }
      else{
        console.log('error retrieving presentation info')
      }
    })
  }

};


