var User = require('../userModel.js'),
    Presentation  = require('./presentationMode.js'),
    Q    = require('q'),
    //jwt  = require('jwt-simple');


module.exports = {
  create: function(req, res, next){
    var title = req.body.title,
        date  = req.body.date,
        userid = req.body.userid,
        findUser = Q.nbind(User.findOne, User),
        create = Q.nbind(Presentation.create, Presentation);

    newPresentation = {
      userid: userId
      title: title, 
      date: date,
      scores: []
    };
  //create a new presentation in the database
  create(newPresentation)
  .then(function(presentation){
    //id for models automatically generated by mongoose
      var presentationId = presentation.id;
      var userId = presentation.userId;
      return findUser({userid: userid})
  })
  .then(function(user) {
      if (user) {
      //go into specific user, add to their preentations array
      user.presentations.push(presentationId);
      //send this event id back to the client 
      res.json({event_id: event_id})
      } else {
      console.log('error finding user');
      }
  })

  /* is this possible?
    var justcreated = create(newPresentation)

    
  */
  },
  //obtain presentation data from a given date by id
  onePres: function(req, res, next){
    //presentationId might be retrievable from URL
    var presentationId = req.body.presentationId;

    var findPres = Q.nbind(Presentation.findOne, Presentation);

    findPres({presentationId: presentationid})
    .then(function(presentation){
      if(presentation){
        res.json(presentation.scores);
      }
      else{
        console.log('error retrieving presentation info')
      }
    })
  }


